### ISSUE TITLE
Make the output deterministic

### ISSUE THREAD

**Issue by Kangz** [Unvanquished/Unvanquished-CBSE#19]
For now some lists are passed in the templates whose order depends on the phase of the moon and python's random. It makes for ugly patches as soon as you will check in the autogenerated files so it would be better to have a deterministic output

**Comment by Viech** [comment]
If it's just about being determinisitc and not about being sorted we could use `collections.OrderedDict` instead of `dict`. Otherwise there is a [sorted dictionary](http://www.grantjenks.com/docs/sortedcontainers/sorteddict.html) but unfortunately it's no standard library and not widely available either.

**Comment by Kangz** [comment]
Sorted would be better though.
